### ISSUE TITLE
Update github action for release with supported repo for the create release step.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap-packagist#31]
https://github.com/actions/create-release has been archived.
In our other repos, we use: https://github.com/softprops/action-gh-release
Let's change
```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: "${{ env.RELEASE_SHA }}"
          tag_name: "v${{ github.event.client_payload.version }}"
          release_name: "v${{ github.event.client_payload.version }}"
          draft: false
          prerelease: false #${{ contains(env.AZ_VERSION, '-alpha') }}

```
to
```
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "v${{ github.event.client_payload.version }}"
          name: "v${{ github.event.client_payload.version }}"
          draft: false
          prerelease: false

```
